### PR TITLE
Fixed some models' symmetry

### PR DESCRIPTION
**Pull request by PatPL**
https://github.com/linuxgurugamer/SXTContinued/issues/68

### CODE REVIEW

**Comment by linuxgurugamer** [comment]
I'm merging into a branch to test first
Thank you

**Comment by linuxgurugamer** [comment]
Looks good, I'll merge to master either later today or tomorrow

**Comment by linuxgurugamer** [comment]
Since you seem to be good with Blender, I was wondering if you could take a look at this problem:

https://forum.kerbalspaceprogram.com/index.php?/topic/183715-parachute-deploys-in-wrong-direction-sometimes/

Being a total beginner at Blender, I don't see anything wrong

**Comment by PatPL** [comment]
I'll take a look (Even though I'm not skilled in blender at all). The rotating you wrote about is actually expected. Blender's 'up' axis is Z, and Unity's 'up' axis is Y. When I worked with SSTU models for GE, every new object added to the model was rotated.

Thing is, once you export it, reimport it, fix the rotation, and export it again, the objects' rotation stays correct forever.

**Comment by linuxgurugamer** [comment]
I saw that the rotation was correct when I looked at some other parts (stock chutes, stock tailfin).  But there must be something wrong because there are two issues there:
1.  Sometimes parachutes deploys the animation in the wrong directoin
2.  Possibly related, the rudder sometimes goes reverse (ie:  input left rudder, it shows right rudder).
Whatever you can do will be appreciated
Thanks

**Comment by PatPL** [comment]
Looks like the rotations of objects on the model might be the issue. The chutes work correctly only when node_attach's rotation is set on Up Z
`node_attach = 0.0, 0.0, 0.0, 0.0, 0.0, 1.0` or 
`node_attach = 0.0, 0.0, 0.0, 0.0, 0.0, -1.0`
(If all of the chutes go the wrong way, toggle the `invertCanopy = false` in ModuleParachute)



But that made the part incorrectly rotated when placed, so I rotated the model, and everything was OK. But the control surfaces broke... (Airbrakes work fine though)



[Here are the files (Broken control surfaces)](https://volafile.org/r/w7r3c2v4)
I rotated a bunch of parts and I have no idea how to fix the control surfaces; I don't know how do they work.

**Pull request merged**
