### PR TITLE
Many small changes.

### PR DESCRIPTION
**Pull request by voicey99**
Cut whitespace slightly, replaced spaces with proper tab spacing and removed superfluous lines across all parts making the configs slightly smaller and easier to follow (unless it's converted into some godawful horizontal format).

Some of the more relevant changes include extending float curves for all engines that didn't have them already to beyond 1atm (sorry, Eve landers, as per #35 ), correcting a few descriptions (grammar, spelling, old references etc.) and increasing the fuel capacity (and dry cost/mass to match) of the Oscar-C, since its fuel capacity was terrible for its size.

### CODE REVIEW

**Comment by miki-g** [comment]
o.O
I was curious about what's changed
O.o
(: [but do not mix changes and reformattings in the future](https://upload.wikimedia.org/wikipedia/en/3/31/Don%27t-overload-your-trailer.jpg) :)
/o\\

**Comment by linuxgurugamer** [comment]
188 files is a lot to review.

I've merged your changes into a new branch which I'll look at, but given the number of files, it's going to take a while.   A separate branch will also make it easier for others to test

I saw a lot of whitespace changes, those should have been done separately, they just clutter up the PR.

Thanks for the work, I'll be reviewing it.

**Comment by linuxgurugamer** [comment]
Just an FYI, I haven't reviewed the fuel capacity for the tanks, so I don't know if the capacity of the Oscar-C is ok or not

**Comment by voicey99** [comment]
It had the same volume (i.e. as long as) as seven Oscar-Bs, so I simply increased its stats (capacity, mass and cost) to be seven times that of the B. I've gone over my maths and everything seems to check out.

**Comment by linuxgurugamer** [comment]
Ok.  Just an FYI, I have a spreadsheet which I used to update all the KWRocketry volumes and masses, I just haven't applied it to this mod yet. 
So while your method was fine, it's just that the basis for your calculations may be changing in the future.  I just wanted to you know that I appreciate your efforts, and that if/when it changes, it won't be because of anything you did wrong.

**Pull request merged**
