### PR TITLE
Remove duplicate pass specifier from CLS_Aviation

### PR DESCRIPTION
**Pull request by ts826848**

### CODE REVIEW

**Comment by linuxgurugamer** [comment]
Already in my local changes, thanks

**Comment by linuxgurugamer** [comment]
Please refresh your fork and check.  It's definitely in the master branch

**Comment by ts826848** [comment]
It wasn't in the version of SXT that was available on SpaceDock when I opened the PR, but it's fixed now. Thanks!

**Comment by linuxgurugamer** [comment]
Ok, then we just crossed wires.
Glad it's working, and thanks for submitting the PR

**Pull request closed without merging**
