### PR TITLE
SXT Beta fixes & updates

### PR DESCRIPTION
**Pull request by PhineasFreak**
- Fix model path for the nuclear RAM jet engine.
- Fix the surface attachment node of the OX-HEX Photovoltaic Panel.
- Fix the displayed names for the FL-S3 Petal Adapter.
- Fix some texture paths.
- Remove the 0.625m heat shield (now a stock part).
- Fix the name of the 5m procedural fairing base.
- Move the cargo bays, the payload fairing bases and the Mk3 ramp to the "Payload" category.
- Move the antenna parts to the "Communication" category.
- Remove a duplicate of the ModuleDataTransmitter module from the Communotron DTS-R4.
- Move the crewed fuselage parts to the "Utility" category.
- Move the Mk0 & Mk1 fuselages to the "FuelTank" category.
- Move the landing airbags and wheels to the "Ground" category.
- Add missing decoupler FX where applicable.
- Move the N1 and Saturn V decouplers to the "Coupling" category.

Edit: there is a 0.625m air intake (SXTInlineAirIntakeTiny") but stock also ships one ("miniIntake"). The differences between the two are minimal so is this another duplicated part?

### CODE REVIEW

**Comment by linuxgurugamer** [comment]
I had a small merge conflict, with the solar hex part:
GameData/SXT/Parts/StationsBases/Electrical/solarHex/part.cfg
Would appreciate your downloading and checking to be sure everything was merged properly.
Thanks

**Comment by PhineasFreak** [comment]
Hmm, i was working with the latest SXT Contrinued configs. What was the conflict?

**Comment by linuxgurugamer** [comment]
I don't remember, but I think it was that I had fixed the same thing you had fixed

**Comment by PhineasFreak** [comment]
Oh, OK then. I was asking out of curiosity.

**Comment by linuxgurugamer** [comment]
no problem, I really appreciate the PRs

**Pull request merged**
